services:
  httpd:
    image: httpd:2.4
    container_name: httpd
    volumes:
      # - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./httpd/index.html:/usr/local/apache2/htdocs/index.html:ro
    networks:
      - web
    ports: []
    restart: always

  nginx:
    image: nginx:mainline
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - httpd
    networks:
      - web
    restart: always

networks:
  web:
    driver: bridge
